### POST
POST https://g12-football-br.onrender.com/bet
Content-Type: application/json

{
  "matchId": "684c79b2f46197c82d1476e7",
  "username": "JOAO",
  "prediction": {
    "homeTeam": 4,
    "awayTeam": 0
  },
  "round": 12
}

### A
GET localhost:8080/bet/round/13/bettors-count

