### POST
POST https://g12-football-br.onrender.com/bet
Content-Type: application/json

{
  "matchId": "689f3741a6af378b823f5de9",
  "username": "apagar",
  "prediction": {
    "homeTeam": 4,
    "awayTeam": 0
  },
  "round": 13
}

### A
GET localhost:8080/bet/round/13/bettors-count
